name = "citta-futura-bookings"
main = "src/index.ts"
compatibility_date = "2024-10-22"

[vars]
GITHUB_REPOSITORY = "<org>/<repo>"
DEFAULT_LABELS = "prenotazione"
ALLOWED_ORIGINS = "https://<your-pages-domain>"

[observability]
enabled = true
